# Generated by Django 3.0.7 on 2020-06-10 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stocl',
            new_name='stock',
        ),
    ]
